version: '3'
services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend code
      dockerfile: Dockerfile  # Use the Dockerfile for your frontend
    ports:
      - "3000:3000"  # Assuming your frontend runs on port 3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Use the Dockerfile for your backend
    ports:
      - "5000:5000"  # Assuming your backend runs on port 5000
